// Command reasonix-worker is the headless daemon binary for remote build
// machines. It polls the reasonix server work queue, claims items, executes
// them in Docker containers, and streams events back.
//
// Usage:
//
//	reasonix-worker --config worker.toml
//
// The worker has no TUI — it runs as a systemd service with security
// hardening. See the bootstrap script generated by `reasonix remote bootstrap`
// for setup instructions.
package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	"os"

	"reasonix/internal/worker"
)

func main() {
	configPath := flag.String("config", "worker.toml", "Path to worker.toml configuration file")
	flag.Parse()

	cfg, err := worker.Load(*configPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "configuration error: %v\n", err)
		os.Exit(1)
	}

	log.Printf("reasonix-worker %q starting", cfg.Name)
	w := worker.New(cfg)
	if err := w.Run(context.Background()); err != nil {
		log.Printf("worker stopped: %v", err)
		os.Exit(1)
	}
}
